# Generated by Django 5.2.1 on 2025-05-24 00:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='manga',
            name='rate',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='mangachapter',
            name='chapter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.manga'),
        ),
        migrations.AddField(
            model_name='mangachapterpage',
            name='chapter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.mangachapter'),
        ),
        migrations.AddField(
            model_name='mangachapterpage',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='novel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='novel',
            name='rate',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='novelchapter',
            name='chapter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.novel'),
        ),
        migrations.AddField(
            model_name='novelchapter',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='MangaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.comment')),
                ('manga', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.manga')),
            ],
        ),
        migrations.CreateModel(
            name='NovelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.comment')),
                ('novel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.novel')),
            ],
        ),
        migrations.CreateModel(
            name='NovelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.novel')),
                ('tag', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tag')),
            ],
        ),
        migrations.CreateModel(
            name='MangaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend.manga')),
                ('tag', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tag')),
            ],
        ),
    ]
