# Generated by Django 5.2.1 on 2025-05-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_manga_rate_alter_novel_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='tags',
            field=models.ManyToManyField(to='backend.tag'),
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(to='backend.tag'),
        ),
    ]
