# Generated by Django 5.2.1 on 2025-05-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='rate',
        ),
    ]
