# Generated by Django 5.2.1 on 2025-05-24 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MangaChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('number', models.IntegerField(default=1)),
                ('chapter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediadex.manga')),
            ],
        ),
        migrations.CreateModel(
            name='MangaChapterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('file', models.FileField(default=None, upload_to='')),
                ('chapter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediadex.mangachapter')),
            ],
        ),
        migrations.CreateModel(
            name='MangaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediadex.comment')),
                ('manga', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediadex.manga')),
            ],
        ),
        migrations.CreateModel(
            name='NovelChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('number', models.IntegerField(default=1)),
                ('text', models.TextField(default='')),
                ('chapter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediadex.novel')),
            ],
        ),
        migrations.CreateModel(
            name='NovelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediadex.comment')),
                ('novel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediadex.novel')),
            ],
        ),
        migrations.CreateModel(
            name='NovelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediadex.novel')),
                ('tag', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='mediadex.tag')),
            ],
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(to='mediadex.tag'),
        ),
        migrations.CreateModel(
            name='MangaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mediadex.manga')),
                ('tag', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='mediadex.tag')),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='tags',
            field=models.ManyToManyField(to='mediadex.tag'),
        ),
    ]
